export type Question = {
  id: number;
  category: "动画" | "小说";
  prompt: string;
  answer: string;
  distractors: [string, string];
};

export const QUESTION_BANK: Question[] = [
  { id: 1, category: "动画", prompt: "截至题库编写时，不计《短物语》《混物语》等，已发行的《物语系列》小说共有多少部？", answer: "30部", distractors: ["28部", "32部"] },
  { id: 2, category: "动画", prompt: "《化物语》中，战场原与历边吃便当边商量约会时，她的便当盒是什么样式？", answer: "分体式", distractors: ["一体式", "双层抽屉式"] },
  { id: 3, category: "动画", prompt: "战场原黑仪与阿良良木历第一次约会的日期是？", answer: "6月13日", distractors: ["5月14日", "7月7日"] },
  { id: 4, category: "动画", prompt: "星空约会中，战场原说自己目前能够给予阿良良木君的最后一样东西是什么？", answer: "这片星空", distractors: ["一只订书机", "她全部的秘密"] },
  { id: 6, category: "动画", prompt: "在卧烟伊豆湖的推断中，忍野扇诞生过程的第二阶段以哪件事为代表？", answer: "与初代怪异杀手的对决", distractors: ["解决北白蛇神社的蛇神事件", "阿良良木历从地狱归来"] },
  { id: 10, category: "动画", prompt: "《抚子与你！》中，男主角、抚子就读的学校与年级分别是？", answer: "北极星速／私立15学园／初二", distractors: ["蜡烛泽君／直江津中学／初三", "阿良良木历／栂之木第二中学／初一"] },
  { id: 14, category: "动画", prompt: "真宵姐姐为什么说朽绳是“镜子的专家”？", answer: "“镜”的语源是蛇的眼睛“蛇目”", distractors: ["白蛇能在镜中看见人的过去", "朽绳曾长期附身在神社的神镜上"] },
  { id: 16, category: "动画", prompt: "历前往神原家时被猴子袭击，又被障猫所救；之后他做的第一件事是？", answer: "去书店买小黄书", distractors: ["去废弃补习班找忍野", "给战场原打电话报平安"] },
  { id: 18, category: "动画", prompt: "真宵姐姐所说的“科幻小说三大帅气标题”中，除《唯一巧妙的做法》《仿生人会梦见电子羊吗？》外，第三个是？", answer: "《月亮是无情的夜之女王》", distractors: ["《世界尽头与冷酷仙境》", "《银河系漫游指南》"] },
  { id: 19, category: "动画", prompt: "历进入镜世界后第一次见到火怜时，火怜的内衣是什么颜色？", answer: "粉色", distractors: ["红色", "黑色"] },
  { id: 20, category: "动画", prompt: "镜世界事件当天早上，历幻想自己被警察盘问身份时，会怎样回答？", answer: "阿良良木历，就是如你所见的男人。", distractors: ["我是正义的伙伴，阿良良木历。", "只是个路过的高中毕业生而已。"] },
  { id: 22, category: "动画", prompt: "斧乃木提出解决镜世界最简单的方法时，引用了什么观点？", answer: "哥白尼式的回转", distractors: ["奥卡姆剃刀", "拉普拉斯的恶魔"] },
  { id: 24, category: "动画", prompt: "“如果不能成为药，那就变成毒；否则你只不过是一杯水。”这句话最可能是谁说的？", answer: "卧烟远江", distractors: ["贝木泥舟", "影缝余弦"] },
  { id: 25, category: "动画", prompt: "忍野扇质问历为何连只会批判、责怪他的自己也要救时，历怎样回答？", answer: "我救的不是别人，我现在救的是我自己。", distractors: ["因为我不允许任何人在我面前消失。", "救你没有意义，但我不需要意义。"] },
  { id: 27, category: "动画", prompt: "神原无意识袭击历之后，给自己加上了怎样的限制？", answer: "用胶带把左臂固定在墙上", distractors: ["睡觉时给左手戴上手铐", "把雨魔的左手封进木箱"] },
  { id: 31, category: "动画", prompt: "神原发短信说自己被以前认识的女孩子揉胸后，历回了什么？", answer: "请带我一个！", distractors: ["请立刻报警！", "请务必详细说明！"] },
  { id: 32, category: "动画", prompt: "中学时代，身为篮球高手的神原骏河有怎样的外号？", answer: "神速天使神原", distractors: ["直江津的雨魔", "瓦尔哈拉组合王牌"] },
  { id: 35, category: "动画", prompt: "贝木因上一辈的缘故特别关照神原，请她吃烤肉时付了多少钱？", answer: "5万日元", distractors: ["3万日元", "10万日元"] },
  { id: 38, category: "动画", prompt: "《伪物语》中，战场原持有的贝木名片上，他给自己写的 title 是？", answer: "Ghost-Buster", distractors: ["Occult Researcher", "Spiritual Counselor"] },
  { id: 40, category: "动画", prompt: "《伪物语》中，小忍认为比“摸头”更高一级的仪式是？", answer: "摸胸", distractors: ["拥抱", "亲吻额头"] },
  { id: 42, category: "动画", prompt: "《终物语·下》最后的毕业照片上一共有多少人？", answer: "11人", distractors: ["9人", "13人"] },
  { id: 43, category: "动画", prompt: "贝木泥舟正装领口的装饰符号，是扑克牌四种花色中的哪一种？", answer: "梅花 ♣", distractors: ["黑桃 ♠", "方块 ♦"] },
  { id: 46, category: "动画", prompt: "历问“八九寺，人什么时候才能长大成人呢？”，八九寺如何回答？", answer: "只要嘴上还挂着这种话，那就长不大。", distractors: ["等到不再害怕迷路的时候吧。", "能够为自己的选择负责时就长大了。"] },
  { id: 49, category: "动画", prompt: "《终物语·下》中，忍野扇与阿良良木历的自行车锁密码分别是？", answer: "扇：1234／历：1345", distractors: ["扇：1345／历：1234", "扇：0000／历：0315"] },
  { id: 51, category: "动画", prompt: "“美丽公主”曾试图用什么工具戳瞎自己的眼睛？", answer: "烛台", distractors: ["发簪", "裁纸刀"] },
  { id: 55, category: "动画", prompt: "殊杀尊主的口头禅、或者说标志性台词是？", answer: "看来，我又死了一次。", distractors: ["这次总算轮到我杀你了。", "死亡不过是下一场战斗。"] },
  { id: 57, category: "动画", prompt: "《忍物语》中，历乱入日伞家的睡衣派对后，现场一共有多少人？", answer: "8人", distractors: ["6人", "9人"] },
  { id: 58, category: "动画", prompt: "春假时大忍说人类对她而言是“食物”；《忍物语》中小忍的回答变成了什么？", answer: "是怪物吧。", distractors: ["是眷属吧。", "是朋友吧。"] },
  { id: 59, category: "动画", prompt: "卧烟伊豆湖说，当下之急是建立一个什么部门？", answer: "风说课", distractors: ["怪异对策室", "传闻管理局"] },
  { id: 66, category: "动画", prompt: "解决黑羽川并确认忍野咩咩离开后，历等人不约而同地认为咩咩是“哪个”？", answer: "滥好人", distractors: ["大骗子", "胆小鬼"] },
  { id: 67, category: "动画", prompt: "历为了确认自己是否喜欢羽川，问月火何时、为何喜欢上“蜡烛泽”；月火的回答是？", answer: "自然而然的。", distractors: ["从第一次见面开始。", "因为他曾经帮助过我。"] },
  { id: 72, category: "动画", prompt: "“不幸的女孩子只会更萌，不是吗？我只是想要解决我的——”空缺处是？", answer: "欲求不满", distractors: ["好奇心", "正义感"] },
  { id: 73, category: "动画", prompt: "第一次黑羽川事件中，为从根本上解决羽川的家庭压力，忍野咩咩大胆提出什么建议？", answer: "让历和羽川结婚", distractors: ["让羽川搬进战场原家", "让羽川离家旅行一年"] },
  { id: 74, category: "动画", prompt: "历曾想过，有一句话自己一辈子都不会对羽川翼说。这句话是？", answer: "喜欢羽川翼。", distractors: ["我什么都知道。", "请你救救我。"] },
  { id: 75, category: "小说", prompt: "《恋物语》中，贝木为什么没有答应请斧乃木吃热巧克力司康？", answer: "斧乃木刚才侮辱他像阿良良木", distractors: ["店里已经卖完了司康", "斧乃木拒绝提供撫子的情报"] },
  { id: 76, category: "小说", prompt: "《化物语》中，历与战场原在家一起学习时抄写的是哪篇英语文章？", answer: "林肯的葛底斯堡演说", distractors: ["马丁·路德·金《我有一个梦想》", "《独立宣言》序言"] },
  { id: 77, category: "小说", prompt: "剧情开始前，战场原就注意到了阿良良木，理由是什么？", answer: "因为观察吊车尾很有趣", distractors: ["因为他在春假突然缺席", "因为羽川经常提起他"] },
  { id: 78, category: "小说", prompt: "战场原黑仪在初中时最喜欢的运动是？", answer: "投标枪", distractors: ["短跑", "跳高"] },
  { id: 80, category: "小说", prompt: "高二时，历错过班级组织的试胆大会，直接原因是什么？", answer: "没人知道他的电话号码，无法邀请", distractors: ["他去补习班照顾小忍", "他误记了活动日期"] },
  { id: 81, category: "小说", prompt: "月火经常参加志愿活动，理由是什么？", answer: "偶尔惹事也能被原谅", distractors: ["为了积累升学需要的履历", "为了监视火怜的正义活动"] },
  { id: 82, category: "小说", prompt: "八九寺问“天国”会让历联想到什么，历思索后给出的答案是？", answer: "真要说的话，就是羽川吧。", distractors: ["真要说的话，就是战场原吧。", "真要说的话，就是小忍吧。"] },
  { id: 84, category: "小说", prompt: "《物语系列》为何又被称作“蚁物语”？", answer: "副音轨中与蚂蚁有关的话题出现频率很高", distractors: ["“物语”的日文写法形似蚂蚁", "西尾维新早期曾计划以蚁怪异为主角"] },
  { id: 85, category: "小说", prompt: "《历·种子》中，阿良良木说出的座右铭是什么？", answer: "对女童温柔。", distractors: ["朋友不需要很多。", "人只能自己救自己。"] },
  { id: 86, category: "小说", prompt: "《忍·铠甲》中，神原用什么例子形容自己为历操心时的悲伤？", answer: "喜欢的歌手出精选集，却没收录自己喜欢的歌", distractors: ["支持的篮球队进入决赛，却输在最后一秒", "买到期待已久的小说，发现缺了最后一页"] },
  { id: 87, category: "小说", prompt: "斧乃木用什么比喻回应历“有没有想做的事或想要的东西”？", answer: "就像问马克杯更喜欢装红茶还是咖啡", distractors: ["就像问人偶更喜欢晴天还是雨天", "就像问剪刀更喜欢裁纸还是布料"] },
  { id: 89, category: "小说", prompt: "卧烟远江指出羽川与伊豆湖共同忽略了知识中的哪种情形？", answer: "以为自己知道，实际却以错误方式理解", distractors: ["知道得越多，就越难采取行动", "不知道本身也可能是一种才能"] },
  { id: 90, category: "小说", prompt: "历说自己不擅长背诵所以历史很差时，羽川如何回应？", answer: "只要有心，世界史和日本史的答案也能用公式导出", distractors: ["历史不是背诵，而是理解人物的选择", "把年代编成顺口溜就完全不会忘记"] },
  { id: 91, category: "小说", prompt: "历问羽川有没有打工的想法时，羽川怎样回答？", answer: "觉得自己还没有足够的价值在社会中工作", distractors: ["校规禁止学生从事任何兼职", "想等高中毕业后再专心工作"] },
  { id: 92, category: "小说", prompt: "羽川放学后为何只去镇上的图书馆，而不去校内图书馆？", answer: "学校图书馆的书已经全读完了", distractors: ["学校图书馆禁止借阅怪异相关书籍", "镇图书馆闭馆更晚、离家更远"] },
  { id: 93, category: "小说", prompt: "直江津高中不禁止染发，历曾表示想看羽川的什么发型？", answer: "茶发卷毛", distractors: ["金色双马尾", "银色齐耳短发"] },
  { id: 95, category: "小说", prompt: "羽川中学时曾有一段时间没有作业可写，原因是什么？", answer: "班主任不想打扰羽川学习", distractors: ["她提前写完了整学期的作业", "学校认为她不需要参加家庭作业"] },
];
